REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'netherwing'@'localhost';

DROP USER 'netherwing'@'localhost';

DROP DATABASE IF EXISTS `world`;

DROP DATABASE IF EXISTS `characters`;

DROP DATABASE IF EXISTS `auth`;

DROP DATABASE IF EXISTS `hotfixes`;

DROP DATABASE IF EXISTS `shop`;